# -*- coding: utf-8 -*-
"""identifyImage.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RK8tb_n3rR9b-Rm0PH-qSKEiqjIpbP5z
"""

import tensorflow as tf
import numpy as np
import cv2

print('tensorflow version: ' + tf.__version__)
print('numpy version: ' + np.__version__)
print('opencv version: ' + cv2.__version__)

# initialize pre trained model
model = tf.keras.applications.MobileNetV2(weights='imagenet')

#store image path
src = ''
while '.png' not in src and '.jpg' not in src:
  src = input('enter image path, must be in same directory (*.png, *.jpg): ')

# process image
image = cv2.imread(src)

#resize image
image = cv2.resize(image, (224,224))

# convert color of image
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# expand dimensions of image array
image = np.expand_dims(image, axis=0)

#preprocess image
image = tf.keras.applications.mobilenet_v2.preprocess_input(image)

# get predictions from model
predict = model.predict(image)

#decode predictions, get 5
decode = tf.keras.applications.mobilenet_v2.decode_predictions(predict, top=1)

#print best match
print('this is an image of: ' + decode[0][0][1])

